title: Aktun Adventures
description: Join us as we chronicle our adventures through Aktun.
baseurl: "/Aktun-Adventures"
url: "http://zalasta.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Minima theme settings
minima:
  skin: solarized

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
